modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="discordbridge"
version="0.0.1-1.18.2"
displayName="Better Discord Bridge"
logoFile=""
description='''
A mod to bridge Minecraft chat with a Discord server.
'''

authors="Kenvaid"
credits="Your Team"
